config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'                         # ホーム画面
  get  'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end
 
  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      redirect_to controller: :inquiry, action: :index
    end
  end
 
  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver
 
    # 完了画面を表示
    render :action => 'thanks'
  end

  private

  def inquiry_params
    # permitの中身は実際のテーブルに合わせて設定
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/inquiry/_footer.html.haml
.inquiry-footer
  %h2.inquiry-footer-text Copyright&copy;ATSUSHI. All Rights Reserved.</>

app/views/inquiry/confirm.html.haml
= render "/projects/header"
.wrap
  = form_for @inquiry, :url => inquiry_thanks_path do |f|
    %h1
      お問い合わせ
    .box-wrap
      .box
        .form-header
          .item-name
            お名前
        .text-wrap
          = f.hidden_field :name
          = @inquiry.name
      .box
        .form-header
          .item-name
            メールアドレス
        .text-wrap
          = f.hidden_field :email
          = @inquiry.email
      .box
        .form-header
          .item-name
            メッセージ
        .textarea-wrap
          = f.hidden_field :message
          = simple_format(@inquiry.message)
    .submit-wrap
      = f.submit '送信'
= render "footer"

app/views/inquiry/index.html.haml
= render "/projects/header"
.wrap
  = form_for @inquiry, :url => inquiry_confirm_path do |f|
    .page-header
    - if @inquiry.errors.any?
      .alert.alert-danger{:role => "alert"}
        %strong 入力内容にエラーがあります
        %ul
          - @inquiry.errors.each do |attr, msg|
            %li= msg
    %h1 
      お問い合わせ
    %form{:action => "index.html", :method => "post"}
      .box-wrap
        .box
          .form-header
            .item-name 
              お名前
            .required 
              必須
          .text-wrap
            = f.text_field :name
        .box
          .form-header
            .item-name 
              メールアドレス
            .required 
              必須
          .text-wrap
            = f.text_field :email
        .box
          .form-header
            .item-name 
              メッセージ
            .required 
              必須
          .textarea-wrap
            = f.text_area :message, :cols => 80, :rows => 8
      .submit-wrap
        = f.submit '確認'
= render "footer"

app/views/inquiry/thanks.html.haml
= render "/projects/header"
.wrap
  .page-header
    %h1 お問い合わせ
  %p.thanks
    お問い合わせいただきありがとうございました。
  = link_to '戻る', root_path, data: {"turbolinks" => false}, class: "back-btn"
= render "footer"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", :name => "viewport"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title 時短経理
    = csrf_meta_tags
    %meta{:content => "tUY3183BvqXcgf-64SGlAJYlVEAXVoYwtBDC9U9YRSY", :name => "google-site-verification"}
    %meta{name: "description",content: "経理業務でよく使う計算を数値を入力するだけで簡単に仕訳がわかるアプリです。 振込された金額から仕訳を作成する補助的な役割や支払手形作成時の収入印紙の節約等、幅広い業務に対応しています。"}
    %meta{name: "keywords",content: "時短経理,じたんけいり,jitankeiri,jitan-keiri,時短,経理,経理アプリ,計算アプリ,収入印紙,印紙節約,手形,手形分割,手形計算,源泉計算,配当金計算,利息計算"}
    %link{rel: "stylesheet", href: "https://fonts.googleapis.com/css?family=Open+Sans:700"}
    %link{rel: "stylesheet", href: "https://use.fontawesome.com/releases/v5.11.2/css/all.css"}
    %link{:href => "https://unpkg.com/sanitize.css", :rel => "stylesheet", :type => "text/css"}/
    %script{ src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'    
    = favicon_link_tag '/images/favicon.ico', rel: 'favicon.ico', type: 'favicon'

  %body
  = yield

app/views/projects/_contents1.html.haml
#1.contents
  .contents-1
    %h2 手形分割計算
    .contents-1-wrap
      .contents-1-left
        .contents-1-form
          %form#form1{:action => "", :name => "form1"}
            手形金額入力：
            %input#textbox1{:type => "tel", :value => ""}
        .contents-1-select
          %select{:id => "", :name => ""}
            %option#target1 手形2枚
            %option#target2 手形3枚
        .contents-1-button
          %input#mathButton1.mathButton{:type => "button", :value => "計算"}
          %input#clear1.clearButton{:type => "button", :value => "クリア"}
        .contents-1-comment
          %p ※金額は半角数字で入力してください
          %p ※利用は自己責任でお願いします
        .contents-1-result
          .tegata
            #tegata1.caution
            #tegata2.caution
            #tegata3.caution
          .insi
            #insi1.caution
            #insi2.caution
            #insi3.caution
      .contents-1-right
        .contents-1-data
          %table.contents-1-table
            %tr
              %th 記載金額
              %td 税額
              %th 記載金額
              %td 税額
            %tr
              %th 10万円未満
              %td 非課税
              %td 3千万円を超え5千万円以下
              %td 1万円
            %tr
              %th 10万円以上100万円以下
              %td 200円
              %td 5千万円を超え1億円以下
              %td 2万円
            %tr
              %th 100万円を超え200万円以下
              %td 400円
              %td 1億円を超え2億円以下
              %td 4万円
            %tr
              %th 200万円を超え300万円以下
              %td 600円
              %td 2億円を超え3億円以下
              %td 6万円
            %tr
              %th 300万円を超え500万円以下
              %td 1千円
              %td 3億円を超え5億円以下
              %td 10万円
            %tr
              %th 500万円を超え1千万円以下
              %td 2千円
              %td 5億円を超え10億円以下
              %td 15万円
            %tr
              %th 1千万円を超え2千万円以下
              %td 4千円
              %td 10億円を超えるもの
              %td 20万円
            %tr
              %th 2千万円を超え3千万円以下
              %td 6千円
              %td
              %td

app/views/projects/_contents2.html.haml
#2.contents
  .contents-2
    %h2 預金利息
    .contents-2-wrap
      .contents-2-form
        %form#form2{:action => "", :name => "form2"}
          入金額：
          %input#textbox2{:type => "tel", :value => ""}
      .contents-2-button
        %input#mathButton2.mathButton{:type => "button", :value => "計算"}
        %input#clear2.clearButton{:type => "button", :value => "クリア"}
      .contents-2-comment
        %p ※金額は半角数字で入力してください
        %p ※利用は自己責任でお願いします
      .contents-2-result
      %table.contents-2-table
        %tr.caution
          %th 受取利息 :
          %td#c2risoku
        %tr.caution
          %th 所得税額 :
          %td#c2syotoku
        %tr.caution
          %th 復興税額 :
          %td#c2hukkou
        %tr.caution
          %th 税額合計 :
          %td#c2totalTax
        
        
        

app/views/projects/_contents3.html.haml
#3.contents
  .contents-3
    %h2 非上場株式配当金
    .contents-3-wrap
      .contents-3-form
        %form#form3{:action => "", :name => "form3"}
          入金額：
          %input#textbox3{:type => "tel", :value => ""}
      .contents-3-button
        %input#mathButton3.mathButton{:type => "button", :value => "計算"}
        %input#clear3.clearButton{:type => "button", :value => "クリア"}
      .contents-3-comment
        %p ※金額は半角数字で入力してください
        %p ※利用は自己責任でお願いします
      .contents-3-result
        %table.contents-3-table
          %tr.caution
            %th 配当金額 :
            %td#haitou1
          %tr.caution
            %th 所得税額 :
            %td#syotoku1
          %tr.caution
            %th 復興税額 :
            %td#hukkou1
          %tr.caution
            %th 税額合計 :
            %td#totalTax1     
        
        
        
        

app/views/projects/_contents4.html.haml
#4.contents
  .contents-4
    %h2 上場株式配当金
    .contents-4-wrap
      .contents-4-form
        %form#form4{:action => "", :name => "form4"}
          入金額：
          %input#textbox4{:type => "tel", :value => ""}
      .contents-4-button
        %input#mathButton4.mathButton{:type => "button", :value => "計算"}
        %input#clear4.clearButton{:type => "button", :value => "クリア"}
      .contents-4-comment
        %p ※金額は半角数字で入力してください
        %p ※利用は自己責任でお願いします
      .contents-4-result
        %table.contents-4-table
          %tr.caution
            %th 配当金額 :
            %td#haitou2
          %tr.caution
            %th 所得税額 :
            %td#syotoku2
          %tr.caution
            %th 復興税額 :
            %td#hukkou2
          %tr.caution
            %th 税額合計 :
            %td#totalTax2    

        
        
        
        

app/views/projects/_contents5.html.haml
#5.contents
  .contents-5
    %h2 契約書
    .contents-5-wrap
      .contents-5-form
        %form#form5{:action => "", :name => "form5"}
          金額：
          %input#textbox5{:type => "tel", :value => ""}
      .contents-5-select
        %select{:id => "", :name => ""}
          %option#keiyaku1 不動産、鉱業権、無体財産権、船舶若しくは航空機又は営業の譲渡に関する契約書
          %option#keiyaku2 請負に関する契約書
      .contents-5-button
        %input#mathButton5.mathButton{:type => "button", :value => "計算"}
        %input#clear5.clearButton{:type => "button", :value => "クリア"}
      .contents-5-comment
        %p ※金額は半角数字で入力してください
        %p ※利用は自己責任でお願いします
      .contents-5-result
        %p#c5comment1
        %p#c5comment2
        #keiyaku.caution

app/views/projects/_contents6.html.haml
#6.contents
  .contents-6
    %h2 源泉
    .contents-6-wrap
      .contents-6-form
        %form#form6{:action => "", :name => "form6"}
          手取金額：
          %input#textbox6{:type => "number", :value => ""}
      .contents-6-select
        %select{:id => "", :name => ""}
          %option#gensen1 講演料等報酬の源泉計算
          %option#gensen2 税理士等報酬の源泉計算
      .contents-6-button
        %input#mathButton6.mathButton{:type => "button", :value => "計算"}
        %input#clear6.clearButton{:type => "button", :value => "クリア"}
      .contents-6-comment
        %p ※金額は半角数字で入力してください
        %p ※利用は自己責任でお願いします
      .contents-6-result
        %table.contents-6-table
          %tr.caution
            %th 報酬金額 :
            %td#ghousyuu
          %tr.caution
            %th 所得税額 :
            %td#gsyotoku
          %tr.caution
            %th 復興税額 :
            %td#ghukkou
          %tr.caution
            %th 税額合計 :
            %td#gtotalTax    

        
        
        
        

app/views/projects/_contents7.html.haml
#7.contents
  .contents-7
    %h2 売上代金に係る金銭又は有価証券の受取書
    .contents-7-wrap
      .contents-7-left
        .contents-7-form
          %form#form7{:action => "", :name => "form7"}
            金額：
            %input#textbox7{:type => "text", :value => ""}/
        .contents-7-select
          %select{:id => "", :name => ""}
            %option#target11 受取書2枚
            %option#target12 受取書3枚
        .contents-7-button
          %input#mathButton7.mathButton{:type => "button", :value => "計算"}
          %input#clear7.clearButton{:type => "button", :value => "クリア"}
        .contents-7-comment
          %p ※金額は半角数字で入力してください
          %p ※利用は自己責任でお願いします
        .contents-7-result
          .receipt
            #receipt1.caution
            #receipt2.caution
            #receipt3.caution
          .insi
            #rinsi1.caution
            #rinsi2.caution
            #rinsi3.caution
      .contents-7-right
        .contents-7-data
          %table.contents-7-table
            %tr
              %th 記載金額
              %td 税額
              %th 記載金額
              %td 税額
            %tr
              %th 5万円未満
              %td 非課税
              %td 3千万円を超え5千万円以下
              %td 1万円
            %tr
              %th 5万円以上100万円以下
              %td 200円
              %td 5千万円を超え1億円以下
              %td 2万円
            %tr
              %th 100万円を超え200万円以下
              %td 400円
              %td 1億円を超え2億円以下
              %td 4万円
            %tr
              %th 200万円を超え300万円以下
              %td 600円
              %td 2億円を超え3億円以下
              %td 6万円
            %tr
              %th 300万円を超え500万円以下
              %td 1千円
              %td 3億円を超え5億円以下
              %td 10万円
            %tr
              %th 500万円を超え1千万円以下
              %td 2千円
              %td 5億円を超え10億円以下
              %td 15万円
            %tr
              %th 1千万円を超え2千万円以下
              %td 4千円
              %td 10億円を超えるもの
              %td 20万円
            %tr
              %th 2千万円を超え3千万円以下
              %td 6千円
              %td
              %td

app/views/projects/_footer.html.haml
%footer
  %h2 Copyright&copy;ATSUSHI. All Rights Reserved.</>

app/views/projects/_header.html.haml
%header
  .h-body
    .h-b-conteiner
      .h-b-title
        =link_to image_tag("headerlogo.png",size: '',class: "headerlogo", alt:"headerlogo"), root_path
      .h-b-menu
        %ul.h-b-menulist
          %li
            %i.fas.fa-home
            = link_to 'TOP', root_path, class: "top"
          %li
            %i.fas.fa-question-circle
            .modal_wrap
              %input#trigger{:type => "checkbox"}
              .modal_overlay
                %label.modal_trigger{:for => "trigger"}
                .modal_content
                  %label.close_button{:for => "trigger"} ✖️
                  %h2 ABOUT
                  %p 数値が間違っている場合はお手数ですがCONTACTから連絡お願いします。
                  %p ※利用は自己責任でお願いします
            %label.open_button{:for => "trigger"} ABOUT
          %li
            %i.far.fa-envelope
            = link_to 'CONTACT', 'inquiry', class: "contact"
        .h-b-m-bottom
          .h-b-m-b-left
            %h2 文字サイズ変更
          .h-b-m-b-right
            .h-b-fontsize
              %input#font-m{:checked => "checked", :name => "fontradio", :type => "radio"}
              %label{:for => "font-m"} 標準
              %input#font-l{:name => "fontradio", :type => "radio"}
              %label{:for => "font-l"} 拡大

app/views/projects/_side.html.haml
.side
  .side-btn
    %a{:href => "#1"} 
      %p 手形分割計算
    %i.fas.fa-angle-right
  .side-btn
    %a{:href => "#2"} 
      %p 預金利息
    %i.fas.fa-angle-right
  .side-btn
    %a{:href => "#3"} 
      %p 非上場株式配当金
    %i.fas.fa-angle-right
  .side-btn
    %a{:href => "#4"} 
      %p 上場株式配当金
    %i.fas.fa-angle-right
  .side-btn
    %a{:href => "#5"} 
      %p 契約書
    %i.fas.fa-angle-right
  .side-btn
    %a{:href => "#6"} 
      %p 源泉
    %i.fas.fa-angle-right
  .side-btn
    %a{:href => "#7"} 
      %p 
        売上代金に係る
        %br
        金銭又は有価証券の受取書
    %i.fas.fa-angle-right

app/views/projects/index.html.haml
%body
  #wrapper.clearfix
    = render "header"
    = render "side"
    .main
      = render "contents1"
      = render "contents2"
      = render "contents3"
      = render "contents4"
      = render "contents5"
      = render "contents6"
      = render "contents7"
    = render "footer"